name: pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  test:
    uses: ./.github/workflows/test.yaml
    with:
      pages: true
    permissions:
      contents: read
  pages:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@main
        with:
          enablement: true
      - id: deployment
        uses: actions/deploy-pages@main
