name: test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version-file: '.node-version'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
      - uses: ./.github/actions/site-data
      - run: npm run outdated
      - run: npm test
      - run: npx playwright install --with-deps chromium
      - run: npm run playwright
